apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate-stats
  namespace: go-app
spec:
  backoffLimit: 2
  restartPolicy: Never
  template:
    spec:
      containers:
        - name: db-migrate-stats
          image: xomrkob/db-migrate:latest
          imagePullPolicy: Always
          args: ["-target=stats"]
          envFrom:
            - configMapRef:
                name: stats-service-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: go-app-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: go-app-secret
                  key: DB_PASS