-- 0001_activity_events schema for events-service
-- Stores recorded activity events (feed/unread reads serviced by the events reader)
-- event_id is client-generated by the producer and globally unique
-- the unique index makes enqueued task redeliveries idempotent (INSERT ON CONFLICT DO NOTHING)

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS activity_events (
    id         uuid         NOT NULL DEFAULT gen_random_uuid(),
    event_id   uuid         NOT NULL,
    user_id    uuid         NOT NULL,
    event_type text         NOT NULL,
    stream_id  uuid,
    payload    jsonb,
    read_at    timestamptz,
    created_at timestamptz  NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_activity_events_event_id ON activity_events (event_id);
CREATE INDEX IF NOT EXISTS idx_activity_events_user_created ON activity_events (user_id, created_at DESC);