#!/usr/bin/env bash
# ============================================================
# GoCast — рендер ConfigMap из единого .env (single source of truth)
# Читает корневой .env и генерирует K8s ConfigMap-манифесты
# в deploy/generated/configmaps/. Перед деплоем: make render
# ============================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT}/.env"
OUT_DIR="${ROOT}/deploy/generated/configmaps"
INGRESS_DIR="${ROOT}/deploy/generated/ingresses"
GENERATED_HEADER="# Generated by render-env.sh from ${ENV_FILE#${ROOT}/} — DO NOT EDIT MANUALLY"

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "ERROR: ${ENV_FILE} не найден. Скопируй .env.example в .env" >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "${ENV_FILE}"
set +a

API="${API_DOMAIN:-${DOMAIN}}"
STORAGE="${STORAGE_DOMAIN:-${DOMAIN}}"
CONSOLE="${CONSOLE_DOMAIN:-${DOMAIN}}"
GRAFANA="${GRAFANA_DOMAIN:-grafana.${DOMAIN}}"
EVENTS="${EVENTS_DOMAIN:-events.${DOMAIN}}"
COMMENTS="${COMMENTS_DOMAIN:-comments.${DOMAIN}}"
STATS="${STATS_DOMAIN:-stats.${DOMAIN}}"
FACES="${FACES_DOMAIN:-faces.${DOMAIN}}"
STREAM_SERVICE_URL="${STREAM_SERVICE_URL:-http://stream-service:80}"
SMTP_ADDR="${SMTP_ADDR:-}"
SMTP_USER="${SMTP_USER:-}"
SMTP_FROM="${SMTP_FROM:-no-reply@${DOMAIN}}"
FRONTEND_URL="${FRONTEND_URL:-https://${DOMAIN}}"

mkdir -p "${OUT_DIR}" "${INGRESS_DIR}"

cm () {
  # cm <name> <key=value>...
  local name="$1"; shift
  local file="${name}.yaml"
  {
    echo "${GENERATED_HEADER}"
    echo "apiVersion: v1"
    echo "kind: ConfigMap"
    echo "metadata:"
    echo "  name: ${name}"
    echo "  namespace: go-app"
    echo "data:"
    local k v
    for entry in "$@"; do
      k="${entry%%=*}"
      v="${entry#*=}"
      printf '  %s: "%s"\n' "${k}" "${v}"
    done
  } > "${OUT_DIR}/${file}"
  echo "  generated ${file}"
}

ingress () {
  # ingress <name> <host> <service-name> <service-port> [path] [secret-suffix]
  local name="$1"
  local host="$2"
  local svc="$3"
  local port="$4"
  local path="${5:-/}"
  local tls_secret="${6:-${name}-tls}"
  local file="${name}.yaml"
  {
    echo "${GENERATED_HEADER}"
    echo "apiVersion: networking.k8s.io/v1"
    echo "kind: Ingress"
    echo "metadata:"
    echo "  name: ${name}"
    echo "  namespace: go-app"
    echo "  annotations:"
    echo "    cert-manager.io/issuer: \"ca-issuer\""
    if [[ "${name}" == "stream-service" ]]; then
      echo "    traefik.ingress.kubernetes.io/buffering.maxRequestBodyBytes: \"1073741824\""
    fi
    echo "spec:"
    echo "  tls:"
    echo "    - hosts:"
    echo "        - ${host}"
    echo "      secretName: ${tls_secret}"
    echo "  rules:"
    echo "    - host: ${host}"
    echo "      http:"
    echo "        paths:"
    echo "          - path: ${path}"
    echo "            pathType: Prefix"
    echo "            backend:"
    echo "              service:"
    echo "                name: ${svc}"
    echo "                port:"
    echo "                  number: ${port}"
  } > "${INGRESS_DIR}/${file}"
  echo "  generated ingresses/${file}"
}

echo "Rendering Ingresses from ${ENV_FILE#${ROOT}/} -> ${INGRESS_DIR}"

ingress frontend          "${DOMAIN}"       web-frontend    80 "/"       front-tls
ingress identity-service  "${API}"          identity-service 80 "/auth"   auth-tls
ingress stream-service    "${API}"          stream-service   80 "/stream" stream-tls
ingress minio-api         "${STORAGE}"      minio           9000 "/"      minio-api-tls
ingress minio-console     "${CONSOLE}"      minio           9090 "/"      minio-console-tls
ingress grafana           "${GRAFANA}"      grafana         3000 "/"      grafana-tls
ingress events-service    "${EVENTS}"       events-reader    8080 "/"      events-tls
ingress comments-service  "${COMMENTS}"     comments-reader  8080 "/"      comments-tls
ingress stats-service     "${STATS}"        stats-reader     8080 "/"      stats-tls
ingress faces-service     "${FACES}"        faces-service    80   "/"      faces-tls

echo "Rendering ConfigMaps from ${ENV_FILE#${ROOT}/} -> ${OUT_DIR}"

cm identity-service-config \
  "SERVER_ADDR=:8080" \
  "DOMAIN=${DOMAIN}" \
  "DB_HOST=${DB_HOST}" \
  "DB_PORT=${DB_PORT}" \
  "DB_NAME=${DB_NAME}" \
  "REDIS_ADDR=${REDIS_ADDR}" \
  "ADMIN_EMAIL=${ADMIN_EMAIL}" \
  "AUTH_SERVICE_ADDRESS=${AUTH_SERVICE_ADDRESS}" \
  "AUTH_RATE_LIMIT=${AUTH_RATE_LIMIT:-30}" \
  "CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS}"

cm stream-service-config \
  "SERVER_ADDR=:8080" \
  "DOMAIN=${API}" \
  "DB_HOST=${DB_HOST}" \
  "DB_PORT=${DB_PORT}" \
  "DB_NAME=${DB_NAME}" \
  "KEEP_ORIGINAL_FILE=false" \
  "MODE=release" \
  "CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS}"

cm go-app-config \
  "MINIO_ENDPOINT=${MINIO_ENDPOINT}" \
  "MINIO_BUCKET_NAME=${MINIO_BUCKET}" \
  "MINIO_USE_SSL=${MINIO_USE_SSL}" \
  "MINIO_REGION=${MINIO_REGION}" \
  "REDIS_ADDR=${REDIS_ADDR}" \
  "STREAM_SERVICE_ADDR=stream-service:50051" \
  "JWT_ACCESS_PUBLIC_KEY_URL=http://identity-service:80/auth/public-key" \
  "AUTH_SERVICE_ADDRESS=identity-service:50051"

cm minio-config \
  "MINIO_SERVER_URL=${MINIO_SERVER_URL}" \
  "MINIO_BROWSER=on" \
  "MINIO_BROWSER_REDIRECT_URL=https://${CONSOLE}" \
  "MINIO_DOMAIN=minio" \
  "MINIO_PROMETHEUS_AUTH_TYPE=public" \
  "MINIO_PROMETHEUS_URL=http://minio:9000" \
  "MINIO_REGION=${MINIO_REGION}" \
  "MINIO_API_CORS_ALLOW_ORIGIN=https://${DOMAIN}" \
  "MINIO_API_CORS_ALLOW_HEADERS=Authorization,Content-Type,X-Amz*" \
  "MINIO_API_CORS_ALLOW_METHODS=GET,PUT,POST,DELETE,OPTIONS,HEAD"

cm transcoder-service-config \
  "WORKER_CONCURRENCY=1" \
  "WORKER_SHUTDOWN_TIMEOUT=50m" \
  "METRICS_ADDR=${METRICS_ADDR}" \
  "TRANSCODER_ENCODER=${TRANSCODER_ENCODER:-auto}"

cm thumbnail-service-config \
  "WORKER_CONCURRENCY=1" \
  "WORKER_SHUTDOWN_TIMEOUT=50m" \
  "METRICS_ADDR=${METRICS_ADDR}"

cm faces-service-config \
  "SERVER_ADDR=:8080" \
  "MODE=release" \
  "DB_HOST=${DB_HOST}" \
  "DB_PORT=${DB_PORT}" \
  "DB_NAME=${FACES_DB_NAME:-faces}" \
  "DB_MAX_CONN=${DB_MAX_CONN:-40}" \
  "MINIO_ENDPOINT=${MINIO_ENDPOINT}" \
  "MINIO_BUCKET_NAME=${MINIO_BUCKET}" \
  "MINIO_USE_SSL=${MINIO_USE_SSL}" \
  "JWT_ACCESS_PUBLIC_KEY_URL=http://identity-service:80/auth/public-key" \
  "CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS}" \
  "FACES_MATCH_THRESHOLD=${FACES_MATCH_THRESHOLD:-0.4}" \
  "FACES_UNKNOWN_THRESHOLD=${FACES_UNKNOWN_THRESHOLD:-0.5}" \
  "FACES_MAX_FRAMES=${FACES_MAX_FRAMES:-500}" \
  "FACES_DETECT_THRESHOLD=${FACES_DETECT_THRESHOLD:-0.4}" \
  "STREAM_SERVICE_URL=${STREAM_SERVICE_URL:-http://stream-service:80}"

cm faces-worker-config \
  "WORKER_CONCURRENCY=1" \
  "WORKER_SHUTDOWN_TIMEOUT=50m" \
  "WORKER_RETRY_DELAY=${WORKER_RETRY_DELAY:-30s}" \
  "METRICS_ADDR=${METRICS_ADDR}" \
  "REDIS_DB=2" \
  "FACES_SERVICE_URL=http://faces-service:80" \
  "FACES_INFER_TIMEOUT=${FACES_INFER_TIMEOUT:-600s}" \
  "STREAM_SERVICE_URL=${STREAM_SERVICE_URL}"

cm mailer-service-config \
  "REDIS_ADDR=${REDIS_ADDR}" \
  "REDIS_DB=2" \
  "WORKER_CONCURRENCY=1" \
  "WORKER_SHUTDOWN_TIMEOUT=50m" \
  "METRICS_ADDR=${METRICS_ADDR}" \
  "SMTP_ADDR=${SMTP_ADDR}" \
  "SMTP_USER=${SMTP_USER}" \
  "SMTP_FROM=${SMTP_FROM}" \
  "FRONTEND_URL=${FRONTEND_URL}"

cm events-service-config \
  "SERVER_ADDR=:8080" \
  "MODE=release" \
  "DOMAIN=${EVENTS}" \
  "DB_HOST=${DB_HOST}" \
  "DB_PORT=${DB_PORT}" \
  "DB_NAME=${DB_NAME}" \
  "REDIS_ADDR=${REDIS_ADDR}" \
  "REDIS_QUEUE_DB=3" \
  "WORKER_CONCURRENCY=1" \
  "WORKER_SHUTDOWN_TIMEOUT=50m" \
  "METRICS_ADDR=${METRICS_ADDR}" \
  "JWT_ACCESS_PUBLIC_KEY_URL=http://identity-service:80/auth/public-key" \
  "EVENTS_READ_RATE_LIMIT=${EVENTS_READ_RATE_LIMIT:-120}" \
  "CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS}"

cm comments-service-config \
  "SERVER_ADDR=:8080" \
  "MODE=release" \
  "DOMAIN=${COMMENTS}" \
  "DB_HOST=${DB_HOST}" \
  "DB_PORT=${DB_PORT}" \
  "DB_NAME=${DB_NAME}" \
  "REDIS_ADDR=${REDIS_ADDR}" \
  "REDIS_QUEUE_DB=3" \
  "METRICS_ADDR=${METRICS_ADDR}" \
  "JWT_ACCESS_PUBLIC_KEY_URL=http://identity-service:80/auth/public-key" \
  "STREAM_SERVICE_URL=${STREAM_SERVICE_URL}" \
  "TRUSTED_PROXIES=${TRUSTED_PROXIES:-}" \
  "COMMENTS_READ_RATE_LIMIT=${COMMENTS_READ_RATE_LIMIT:-300}" \
  "CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS}"

cm stats-service-config \
  "SERVER_ADDR=:8080" \
  "MODE=release" \
  "DOMAIN=${STATS}" \
  "DB_HOST=${DB_HOST}" \
  "DB_PORT=${DB_PORT}" \
  "DB_NAME=${STATS_DB_NAME:-stats}" \
  "REDIS_ADDR=${REDIS_ADDR}" \
  "REDIS_QUEUE_DB=3" \
  "REDIS_VIEWS_DB=4" \
  "VIEWS_RATE_LIMIT=${VIEWS_RATE_LIMIT:-300}" \
  "REACTION_RATE_LIMIT=${REACTION_RATE_LIMIT:-30}" \
  "METRICS_ADDR=${METRICS_ADDR}" \
  "JWT_ACCESS_PUBLIC_KEY_URL=http://identity-service:80/auth/public-key" \
  "STREAM_SERVICE_URL=${STREAM_SERVICE_URL}" \
  "TRUSTED_PROXIES=${TRUSTED_PROXIES:-}" \
  "CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS}"

cm grafana-config \
  "GF_SERVER_ROOT_URL=https://${GRAFANA}"

echo "Done. Apply with: kubectl apply -f ${OUT_DIR}/"