#!/usr/bin/env bash
# ============================================================
# GoCast — рендер ConfigMap из единого .env (single source of truth)
# Читает корневой .env и генерирует K8s ConfigMap-манифесты
# в deploy/generated/configmaps/. Перед деплоем: make render
# ============================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT}/.env"
OUT_DIR="${ROOT}/deploy/generated/configmaps"
INGRESS_DIR="${ROOT}/deploy/generated/ingresses"
GENERATED_HEADER="# Generated by render-env.sh from ${ENV_FILE#${ROOT}/} — DO NOT EDIT MANUALLY"

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "ERROR: ${ENV_FILE} не найден. Скопируй .env.example в .env" >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "${ENV_FILE}"
set +a

API="${API_DOMAIN:-${DOMAIN}}"
STORAGE="${STORAGE_DOMAIN:-${DOMAIN}}"
CONSOLE="${CONSOLE_DOMAIN:-${DOMAIN}}"
GRAFANA="${GRAFANA_DOMAIN:-grafana.${DOMAIN}}"

mkdir -p "${OUT_DIR}" "${INGRESS_DIR}"

cm () {
  # cm <name> <key=value>...
  local name="$1"; shift
  local file="${name}.yaml"
  {
    echo "${GENERATED_HEADER}"
    echo "apiVersion: v1"
    echo "kind: ConfigMap"
    echo "metadata:"
    echo "  name: ${name}"
    echo "  namespace: go-app"
    echo "data:"
    local k v
    for entry in "$@"; do
      k="${entry%%=*}"
      v="${entry#*=}"
      printf '  %s: "%s"\n' "${k}" "${v}"
    done
  } > "${OUT_DIR}/${file}"
  echo "  generated ${file}"
}

ingress () {
  # ingress <name> <host> <service-name> <service-port> [path] [secret-suffix]
  local name="$1"
  local host="$2"
  local svc="$3"
  local port="$4"
  local path="${5:-/}"
  local tls_secret="${6:-${name}-tls}"
  local file="${name}.yaml"
  {
    echo "${GENERATED_HEADER}"
    echo "apiVersion: networking.k8s.io/v1"
    echo "kind: Ingress"
    echo "metadata:"
    echo "  name: ${name}"
    echo "  namespace: go-app"
    echo "  annotations:"
    case "${name}" in
      frontend)
        echo "    cert-manager.io/issuer: \"ca-issuer\""
        ;;
      grafana)
        echo "    nginx.ingress.kubernetes.io/backend-protocol: \"HTTP\""
        echo "    cert-manager.io/issuer: \"ca-issuer\""
        ;;
      identity-service|stream-service)
        echo "    nginx.ingress.kubernetes.io/backend-protocol: \"HTTP\""
        echo "    nginx.ingress.kubernetes.io/http2-listener: \"true\""
        echo "    cert-manager.io/issuer: \"ca-issuer\""
        ;;
      minio-console)
        echo "    nginx.ingress.kubernetes.io/use-forwarded-headers: \"true\""
        echo "    nginx.ingress.kubernetes.io/backend-protocol: \"HTTP\""
        echo "    cert-manager.io/issuer: \"ca-issuer\""
        ;;
      minio-api)
        echo "    nginx.ingress.kubernetes.io/use-forwarded-headers: \"true\""
        echo "    cert-manager.io/issuer: \"ca-issuer\""
        ;;
    esac
    if [[ "${name}" == "stream-service" ]]; then
      echo "    nginx.ingress.kubernetes.io/client-max-body-size: \"0\""
      echo "    nginx.ingress.kubernetes.io/proxy-body-size: \"1024m\""
    fi
    echo "spec:"
    echo "  ingressClassName: nginx"
    echo "  tls:"
    echo "    - hosts:"
    echo "        - ${host}"
    echo "      secretName: ${tls_secret}"
    echo "  rules:"
    echo "    - host: ${host}"
    echo "      http:"
    echo "        paths:"
    echo "          - path: ${path}"
    echo "            pathType: Prefix"
    echo "            backend:"
    echo "              service:"
    echo "                name: ${svc}"
    echo "                port:"
    echo "                  number: ${port}"
  } > "${INGRESS_DIR}/${file}"
  echo "  generated ingresses/${file}"
}

echo "Rendering Ingresses from ${ENV_FILE#${ROOT}/} -> ${INGRESS_DIR}"

ingress frontend          "${DOMAIN}"       web-frontend    80 "/"       front-tls
ingress identity-service  "${API}"          identity-service 80 "/auth"   auth-tls
ingress stream-service    "${API}"          stream-service   80 "/stream" stream-tls
ingress minio-api         "${STORAGE}"      minio           9000 "/"      minio-api-tls
ingress minio-console     "${CONSOLE}"      minio           9090 "/"      minio-console-tls
ingress grafana           "${GRAFANA}"      grafana         3000 "/"      grafana-tls

echo "Rendering ConfigMaps from ${ENV_FILE#${ROOT}/} -> ${OUT_DIR}"

cm identity-service-config \
  "SERVER_ADDR=:8080" \
  "DOMAIN=${DOMAIN}" \
  "DB_HOST=${DB_HOST}" \
  "DB_PORT=${DB_PORT}" \
  "DB_NAME=${DB_NAME}" \
  "REDIS_ADDR=${REDIS_ADDR}" \
  "ADMIN_EMAIL=${ADMIN_EMAIL}" \
  "AUTH_SERVICE_ADDRESS=${AUTH_SERVICE_ADDRESS}" \
  "CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS}"

cm stream-service-config \
  "SERVER_ADDR=:8080" \
  "DOMAIN=${API}" \
  "DB_HOST=${DB_HOST}" \
  "DB_PORT=${DB_PORT}" \
  "DB_NAME=${DB_NAME}" \
  "KEEP_ORIGINAL_FILE=false" \
  "MODE=release" \
  "CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS}"

cm go-app-config \
  "MINIO_ENDPOINT=${MINIO_ENDPOINT}" \
  "MINIO_BUCKET_NAME=${MINIO_BUCKET}" \
  "MINIO_USE_SSL=${MINIO_USE_SSL}" \
  "MINIO_REGION=${MINIO_REGION}" \
  "REDIS_ADDR=${REDIS_ADDR}" \
  "STREAM_SERVICE_ADDR=stream-service:50051" \
  "JWT_ACCESS_PUBLIC_KEY_URL=http://identity-service:80/auth/public-key" \
  "AUTH_SERVICE_ADDRESS=identity-service:50051"

cm minio-config \
  "MINIO_SERVER_URL=${MINIO_SERVER_URL}" \
  "MINIO_BROWSER=on" \
  "MINIO_BROWSER_REDIRECT_URL=https://${CONSOLE}" \
  "MINIO_DOMAIN=minio" \
  "MINIO_PROMETHEUS_AUTH_TYPE=public" \
  "MINIO_PROMETHEUS_URL=http://minio:9000" \
  "MINIO_REGION=${MINIO_REGION}" \
  "MINIO_API_CORS_ALLOW_ORIGIN=https://${DOMAIN}" \
  "MINIO_API_CORS_ALLOW_HEADERS=Authorization,Content-Type,X-Amz*" \
  "MINIO_API_CORS_ALLOW_METHODS=GET,PUT,POST,DELETE,OPTIONS,HEAD"

cm transcoder-service-config \
  "WORKER_CONCURRENCY=1" \
  "WORKER_SHUTDOWN_TIMEOUT=50m" \
  "METRICS_ADDR=${METRICS_ADDR}"

cm thumbnail-service-config \
  "WORKER_CONCURRENCY=1" \
  "WORKER_SHUTDOWN_TIMEOUT=50m" \
  "METRICS_ADDR=${METRICS_ADDR}"

cm grafana-config \
  "GF_SERVER_ROOT_URL=https://${GRAFANA}"

echo "Done. Apply with: kubectl apply -f ${OUT_DIR}/"